mongodb database and mocking.
htmlacademy-nodejs/664207-keksobooking pull request #13
Opened 2018-10-15 22:38 UTC by vladimir-rurik

2018-10-16 19:36 UTC, dangreen requested changes

2018-10-16 19:36 UTC, dangreen commented on src/common/data-renderer.js
> +const SUCCESS_CODE = 200;
зачем в конфиге тогда это?

2018-10-16 19:36 UTC, dangreen commented on src/common/config.js
>  module.exports = {
определись, либо ты все тут складируешь , либо по файлм константы
у тебя щас и так и сяк

2018-10-17 09:58 UTC, vladimir-rurik commented on src/common/config.js
>  module.exports = {
removed constants.js, using config.js instead.

2018-10-17 16:47 UTC, merged